### ISSUE TITLE
Play Playlist

### ISSUE THREAD

**Issue by fmarzocca** [emiloberg/node-red-contrib-advanced-mopidy#12]
I am testing this module because I need to start a playlist when an action is triggered, but I can't find how to play a specific playlist. It seems that I can only play single tracks.
Is it true, or am I missing something?

**Comment by DeadEnded** [comment]
I just started testing out this yesterday and just like you found there is not an "add playlist to queue".  I even checked the API and I didn't see anything for it... I found that very odd.

My work around is to use the `playlist.getItems`, and then pass that to `tracklist.add`... but for so reason - I can't seem to get the syntax in `tracklist.add` correct!

If you have this working can you please let me know what the syntax for `tracklist.add` you are using is that works? I've tried many combinations.  Looking at the other issues, this appears to be a common issue...

As far as my idea... here is what I am doing:

![image](https://user-images.githubusercontent.com/45110141/146069224-c047d335-41c3-4dd0-abb2-fd9154fd2dd1.png)

and in the function node:
```
let data = msg.payload;
let i = 1;
let arr = [];
msg.params = [];

while(data[i] != null) {
  arr.push('"' + data[i].uri + '"');
  i++;
}

msg = {
        host: '1.2.3.4',
        port: 6680,
        method:'tracklist.add',
        params: {uris:arr.join(",")}
        };

return msg;
```

This of course will need to be modified based on what I am doing wrong in the `tracklist.add`...

Cheers!
DeadEnd

**Comment by DeadEnded** [comment]
I got it working!
So the output node I can't get to work using tracklist.add and entering uri's directly - but if I use a function node as above it works... just had to fix some of the code - here is my working function node:

```
let data = msg.payload;
let i = 1;
let arr = [];

while(data[i] != null) {
  arr.push(data[i].uri);
  i++;
}

msg = {
        host: '1.2.3.4',
        port: 6680,
        method:'tracklist.add',
        params: {uris:arr}
        };

return msg;
```

Cheers!
DeadEnd

**Comment by fmarzocca** [comment]
[image: Schermata 2021-12-15 alle 08.34.53.png]

Just input the playlist uri.

**Comment by DeadEnded** [comment]
Your image file did not load - so perhaps that will help... but I tried passing the playlist URI and it did not work.
Using the console I even tried `mopidy.tracklist.add({uris:["<playlist_URI>"]});` and it did not throw an error, but also did not add anything to the queue.

I am a novice though - so perhaps I missed something.

**Comment by fmarzocca** [comment]
Before adding the tracklist you need to send to mopidy a getitems with the uri, then send the result to tracklist.add (uris..)

First send getitems with the uri,
```
uri = env.get("uri");
a = {"jsonrpc":"2.0","id":1,"method":"core.playlists.get_items","params":{"uri":uri}}
msg.payload = a;
return msg;
```

then send the payload to tracklist.add:
```
b = msg.payload.result;
a = {"jsonrpc":"2.0","id":1,"method":"core.tracklist.add","params":{"uris":""}}
var list=[];

b.forEach(e => { 
    list.push(e.uri)
});
a.params.uris = list;
msg.payload=a;
return msg;
```

Then play it.

**Comment by fmarzocca** [comment]
<img width="852" alt="Schermata 2021-12-15 alle 19 47 15" src="https://user-images.githubusercontent.com/8530030/146246780-622f40c6-5149-4c93-ac36-d520f21179a8.png">

**Comment by fmarzocca** [comment]
First get the items from the playlist. Then add those track ref uris to the tracklist.

**Comment by DeadEnded** [comment]
yes, that is what I am already doing - I thought you were saying you could pass the playlist URI to the `tracklist.add` directly.  I have what you are showing working using Mopidy nodes instead of HTTP nodes... just took a little research and trial and error.

I have actually just completed about 90% of my flow to control Mopidy with Rhasspy voice assistant.
The last step to do is single song playing... I have the rhasspy side already done, just have to pass the song through the intent to the `tracklist.add` and get that syntax correct.

Playlists are working - as are normal controls.  Stopping and resuming I had to do a work around - which was a pain since I couldn't find a way in Mopidy to do this... I had to save a NR variable of the currently position, stop playback to interact with Rhasspy, and then start playback again and seek to the previous position.  This was caused by the fact that when you pause mopidy playback, it still has control of the audio device, and so Rhasspy couldn't use it.

Anyway, I'm almost done and pretty happy with what I have accomplished.
Here is what it looks like (I'm a novice, so I'm sure others could do it cleaner):
![image](https://user-images.githubusercontent.com/45110141/146275185-db0b2efe-2775-4b2b-acb7-8d7869dabf1a.png)

Updated the image... I finished the single song query using Rhasspy intent... it's messy but it works.

Cheers!
DeaDend

**Comment by VentiloFred** [comment]
> 

Hello @DeadEnded ,
I tried so many combinations to play a song with Mopidy since Node Red but nothing works.
tracklist.clear work
playlists.getitems work
But i cannot add a file to play a song

Can you help me, thanks a lot

![image](https://github.com/emiloberg/node-red-contrib-mopidy/assets/80253334/e5e6024f-5f34-4e10-8470-c7e7b88adada)

**Comment by fmarzocca** [comment]
> Can you help me, thanks a lot
> 

This module seems abandoned. I have developed my own module to manage mopidy through MQTT.
Look here:
[Mopiqtt](https://github.com/fmarzocca/Mopiqtt): https://github.com/fmarzocca/Mopiqtt

**Comment by VentiloFred** [comment]
> > Can you help me, thanks a lot
> 
> This module seems abandoned. I have developed my own module to manage mopidy through MQTT. Look here: [Mopiqtt](https://github.com/fmarzocca/Mopiqtt): https://github.com/fmarzocca/Mopiqtt

Thanks to reply.
I m lost... Mopiqtt is an addon for Mopidy? How to install?
I run Mopidy 2.2.0 - 2022-08-07 since Home Assistant up to date.

**Comment by fmarzocca** [comment]
everything is in the readme... Go to that url.
